= fulcro-spec
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

== Description

A Clojure(scipt) testing library to augment the standard `clojure.test`.

image:https://img.shields.io/clojars/v/fulcrologic/fulcro-spec.svg[link="https://clojars.org/fulcrologic/fulcro-spec"]

Release: image:https://circleci.com/gh/fulcrologic/fulcro-spec/tree/main.svg?style=svg["CircleCI", link="https://circleci.com/gh/fulcrologic/fulcro-spec/tree/main"]

== Usage

[source, clojure]
-----
(ns my-test
  (:require
    [fulcro-spec.core :refer [specification when-mocking provided assertions]]
    [clojure.test :refer [deftest]]
    ...))

(defn f [x] 900)
(defn g [y] (+ y (f y)))

(deftest my-test
  (when-mocking
    (f x) => 22

    (assertions
      "mocking works"
      (g 9) => 31)))
-----

The `specification` macro is a convenient alternative to `deftest` that provides enhanced reporting
and metadata support:

[source, clojure]
-----
;; Basic usage
(specification "My feature works correctly"
  (assertions
    "addition works"
    (+ 1 2) => 3))

;; With selector keywords for test filtering (e.g., :focus)
(specification "Debug this test" :focus
  (assertions
    (+ 1 2) => 3))

;; With custom metadata map for advanced test organization
(specification {:integration true :slow true} "Database integration test"
  (assertions
    (db/query ...) => ...))

;; Combining metadata map with selector keywords
(specification {:integration true} "Critical integration test" :focus
  (assertions
    (critical-operation) => expected-result))
-----

The metadata map (when provided) must appear before the test name string. Selector keywords
(like `:focus`) follow the test name and are automatically converted to metadata. Both metadata
sources are merged, allowing test runners to filter tests by any metadata key.

== REPL Runner

It is common to want to run tests in the REPL, but the output of the default runner leaves a lot to be desired.  If
you're using IntelliJ you can now add something like this to your REPL commands (and hook it to a keyboard shortcut) for a much
better testing experience:

Run Tests with a `:focus` metadata marker (selector):

```
(in-ns (.getName *ns*))
(require 'fulcro-spec.reporters.repl)
(fulcro-spec.reporters.repl/run-tests #(:focus (meta %)))
```

Run all tests:

```
(in-ns (.getName *ns*))
(require 'fulcro-spec.reporters.repl)
(fulcro-spec.reporters.repl/run-tests)
```

See https://github.com/fulcrologic/fulcro-spec/blob/main/docs/index.adoc[the docs] for more details.
